kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
  extraPortMappings:
  - containerPort: 30081
    hostPort: 30081
- role: worker
  extraPortMappings:
  - containerPort: 30082
    hostPort: 30082
- role: worker
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
- role: worker
  extraPortMappings:
  - containerPort: 30083
    hostPort: 30083
- role: worker
  extraPortMappings:
  - containerPort: 30084
    hostPort: 30084